<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title><?= $title ?></title>
        <link rel="stylesheet" href="/js/chosen/chosen.css">
    </head>
    <body>
        <div><a href="/index.php?route=registration">Регистрация</a></div>
        <?= $content ?>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="/js/chosen/chosen.jquery.min.js"></script>
        <script src="/js/main.js"></script>
    </body>
</html>
