 <select name="<?= $name ?>" id="<?= $id ?>" class="chosen-select"<?= $action ? ' data-action="' . $action . '" data-target="' . $target . '"' : '' ?>>
    <option value=""><?= $label ?></option>
    <?php foreach ($options as $option) : ?>
    <option value="<?= $option['ter_id'] ?>"<?= $option['ter_id'] == $field_id ? ' selected' : '' ?>><?= $option['ter_name'] ?></option>
    <?php endforeach; ?>
</select>
<div class="errors"></div>
